"""upd

Revision ID: 008e0d0a03ab
Revises: 56f1cdbac49d
Create Date: 2025-05-23 22:22:42.231320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '008e0d0a03ab'
down_revision: Union[str, None] = '56f1cdbac49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Job', 'SubState',
               existing_type=mysql.ENUM('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'COMPLETED'),
               type_=sa.Enum('CREATED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'RETURNED', 'COMPLETED', name='substate'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Job', 'SubState',
               existing_type=sa.Enum('CREATED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'RETURNED', 'COMPLETED', name='substate'),
               type_=mysql.ENUM('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'COMPLETED'),
               existing_nullable=False)
    # ### end Alembic commands ###
