"""refactoring

Revision ID: 0938afb5485a
Revises: e3261ad784ba
Create Date: 2024-09-18 16:10:00.077188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0938afb5485a'
down_revision: Union[str, None] = 'e3261ad784ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('JobStatus')
    op.add_column('Job', sa.Column('State', sa.Enum('UNASSIGNED', 'ASSIGNED', 'FINISHED', name='state'), nullable=False))
    op.add_column('Job', sa.Column('SubState', sa.Enum('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'FINISHED', 'ABORTED', name='substate'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Job', 'SubState')
    op.drop_column('Job', 'State')
    op.create_table('JobStatus',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('JobId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('State', mysql.ENUM('UNASSIGNED', 'ASSIGNED', 'FINISHED'), nullable=False),
    sa.Column('SubState', mysql.ENUM('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'FINISHED', 'ABORTED'), nullable=False),
    sa.Column('Timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Job.Id'], name='JobStatus_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
