"""upd

Revision ID: 093b4bd6ef3a
Revises: 3e57b48e3759
Create Date: 2025-05-21 21:25:34.783237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '093b4bd6ef3a'
down_revision: Union[str, None] = '3e57b48e3759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JobScheduleEntry',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('ClientId', sa.Integer(), nullable=False),
    sa.Column('Rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ClientId'], ['Client.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['JobId'], ['Job.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('Epoch')
    op.drop_table('Session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Session',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('JobId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MaxEpoch', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Snapshot', mysql.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Job.Id'], name='Session_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Epoch',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('SessionId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('StartTimestamp', mysql.DATETIME(), nullable=False),
    sa.Column('EndTimestamp', mysql.DATETIME(), nullable=False),
    sa.Column('Result', mysql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['SessionId'], ['Session.Id'], name='Epoch_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('JobScheduleEntry')
    # ### end Alembic commands ###
