"""upd

Revision ID: 56f1cdbac49d
Revises: 093b4bd6ef3a
Create Date: 2025-05-22 16:49:14.294284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56f1cdbac49d'
down_revision: Union[str, None] = '093b4bd6ef3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('Result', sa.JSON(), nullable=True))
    op.alter_column('Job', 'SubState',
               existing_type=mysql.ENUM('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'FINISHED', 'ABORTED'),
               type_=sa.Enum('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'COMPLETED', name='substate'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Job', 'SubState',
               existing_type=sa.Enum('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'ABORTED', 'COMPLETED', name='substate'),
               type_=mysql.ENUM('CREATED', 'RETURNED', 'SCHEDULED', 'RUNNING', 'FAILED', 'FINISHED', 'ABORTED'),
               existing_nullable=False)
    op.drop_column('Job', 'Result')
    # ### end Alembic commands ###
