"""jobs

Revision ID: d284725dcf96
Revises: 0938afb5485a
Create Date: 2025-04-25 17:04:10.853572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd284725dcf96'
down_revision: Union[str, None] = '0938afb5485a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('JobData', sa.JSON(), nullable=False))
    op.drop_column('Job', 'Configuration')
    op.drop_column('Job', 'Name')
    op.drop_column('Job', 'Description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('Description', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('Job', sa.Column('Name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('Job', sa.Column('Configuration', mysql.JSON(), nullable=False))
    op.drop_column('Job', 'JobData')
    # ### end Alembic commands ###
