"""added sessions

Revision ID: e3261ad784ba
Revises: 5d7ea004e2a0
Create Date: 2024-09-17 23:45:51.363727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3261ad784ba'
down_revision: Union[str, None] = '5d7ea004e2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Session',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('MaxEpoch', sa.Integer(), nullable=True),
    sa.Column('Snapshot', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Job.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Epoch',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SessionId', sa.Integer(), nullable=False),
    sa.Column('StartTimestamp', sa.DateTime(), nullable=False),
    sa.Column('EndTimestamp', sa.DateTime(), nullable=False),
    sa.Column('Result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['SessionId'], ['Session.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Epoch')
    op.drop_table('Session')
    # ### end Alembic commands ###
