"""job modules

Revision ID: f256f606267d
Revises: d284725dcf96
Create Date: 2025-05-03 00:48:30.054077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f256f606267d'
down_revision: Union[str, None] = 'd284725dcf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('Name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Job', 'Name')
    # ### end Alembic commands ###
